### ISSUE TITLE
Hands-On 3, Part A, Step 10 - "Make Available Through Property Nodes" not checked

### ISSUE THREAD

**Issue by AndrewHeim** [LabVIEW-DCAF/Documentation#100]
In Part A, Step 10, we make accessors:
![not checked!](https://raw.githubusercontent.com/LabVIEW-DCAF/Documentation/master/Trunk/Getting%20Started%20Material/Hands%20On/Hands-On_3/Pictures/CreatingAccessorsforScale.jpg "not checked!")

The pic shows the check mark un-checked, so I unchecked it (even though I usually leave it checked by default... and that might be the LV default).  But we end up wanting to use property nodes right away in Part B step 1:
![Scale is using a property node!]( https://raw.githubusercontent.com/LabVIEW-DCAF/Documentation/master/Trunk/Getting%20Started%20Material/Hands%20On/Hands-On_3/Pictures/ModifiedCreateTestConfiguration.jpg "Scale is using a property node!")

(Note the property node for Scale)

Can we show that check box as selected?

**Comment by SimonRPSM** [comment]
Yep, you are right. Fixed!
