### ISSUE TITLE
LabVIEW-DCAF Org Ownership

### ISSUE THREAD

**Issue by davidcorrigan714** [LabVIEW-DCAF/Documentation#111]
@smithed  or @jacobson3, would you all mind helping us get this org officially under NI's ownership? Not familiar with the project or its history but Rich mentioned this org was a thing we should probably be aware of. If you can add myself as an org owner I can transfer it to be officially under NI's company account - afaik there's no material change to the account's contents or appearance other than it'll say "Part of NI" like https://github.com/ni does and NI can manage it going forward. Thanks!

( Sorry for making this a somewhat unrelated issue on the repo, GH doesn't have direct messaging )

**Comment by jacobson3** [comment]
@davidcorrigan714 The human owners of this org are @becega and @pollockm so I think they would have to help you although neither of them work for NI anymore (neither do smithed or myself).

The two non-human owners are @DCAF-Build and @DCAF-Builder so maybe if you can find someone who knows those credentials you can do it yourself.

**Comment by jacobson3** [comment]
Also does this mean NI is resurrecting DCAF?

**Comment by davidcorrigan714** [comment]
@jacobson3  oh of course, you two are the only public members which isn't indicative of org ownership. I'll poke around for those service accounts in case those other folk aren't around to help out. I'm not aware of any DCAF plans one way or another, maybe Rich was bored or it crossed his mind. Of course with the acquisition there is a lot of house-keeping going on in all sorts of places.

**Comment by smithed** [comment]
@Beazurt is afaik back at NI now and may know who to talk to.

**Comment by rtollert** [comment]
> Also does this mean NI is resurrecting DCAF?

No, it just means I remembered y'all (and I have concerns about NI losing access to stuff)

**Comment by smithed** [comment]
Looks like C. loew is the point of contact listed for nisystemsengineering which was all of the same folks, so he may be able to help as well.

**Comment by cloew-ni** [comment]
@rtollert @davidcorrigan714  Sorry, I didn't see this discussion as I wasn't tagged in it. I believe Benji  (@becega) and Matt (@pollockm ) are the only two owners of the org. I'll reach out to them to get us added as owners.

**Comment by cloew-ni** [comment]
@rtollert I made you owner for this org, and @davidcorrigan714 I invited you as owner as well.

**Comment by jacobson3** [comment]
@rtollert / @cloew-ni there's also a team called "NI Contributor" which you might want to cleanup since a lot of those people don't work at NI anymore.

I don't know what the team is used for or what permissions it gives so might just need a rename.
