### ISSUE TITLE
Hands On - General Documentation Feedback

### ISSUE THREAD

**Issue by SimonRPSM** [LabVIEW-DCAF/Documentation#16]
The Hands On could benefit from having some extra "background information" like what can be found in the introductory DCAF sessions.

For example, a page and a short description with a project screenshot detailing Editor vs Runtime information, which class does what, Tag VS Channel slide, etc, could be reasonably quick to set up but help people going through the Hands On both inside and outside of the class setting. 

An additional comment specific to Excercise 3, it could be helpful to have a diagram/Hierarchy of the VIs to better drive home what they are supposed to be doing.

**Comment by becega** [comment]
This was part of the feedback Luis fixed before the hand on In Alliance Day
