### ISSUE TITLE
Hands On: Update Hands On for NIWeek 2016

### ISSUE THREAD

**Issue by mwjacobson3** [LabVIEW-DCAF/Documentation#18]
Documentation should be updated to change TBDF to DCAF along with a few small changes. I tracked a few suggested changes in the attached document.

[DCAF Hands On.docx](https://github.com/LabVIEW-DCAF/Documentation/files/341918/DCAF.Hands.On.docx)

**Comment by lucamach83** [comment]
This document is the old version og the Hands On document. The new one is inside DCAF Hands On 2016. Some of this changes still apply
