### ISSUE TITLE
Downloading the Hands On from GitHub as a Zip Corrupts the Configuration Files

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/Documentation#23]
Still not certain why this is happening, but directly downloading the hands on material from github as a .zip file can change the end of line characters in the configuration files making them error when opened. We should post the hands on materials directly on the community to prevent other users from running into this.

**Comment by smithed** [comment]
Neat. git/linux is ~~trolling you~~ behaving as expected, but there is an easy fix it looks like: 
http://stackoverflow.com/questions/17347611/downloading-a-zip-from-github-removes-newlines-from-text-files

I guess you just need to figure out the arcane syntax to unset the "text" property on platycfg files:
https://git-scm.com/docs/gitattributes
