### ISSUE TITLE
Learning Path Diagram

### ISSUE THREAD

**Issue by SimonRPSM** [LabVIEW-DCAF/Documentation#25]
As part of reworking DCAF content should we create a main diagram of the possible DCAF learning paths? 

This could be used as the first document someone who wants to learn about DCAF sees and we can use it to highlight specific content when there are things that overlap.

This is from Miles' feedback.

**Comment by becega** [comment]
We could add it to the readme file on the documentation page, similar to what we have with the hands On. and as we are moving the documentation to MD or webpages we could just make a central place for all the links

**Comment by SimonRPSM** [comment]
I have been investigating moving the documentation to ReadTheDocs vs having a series of Readme files (such that they show up when browsing repos). For now we have added some hubs that link to other documents.
