### ISSUE TITLE
DCAF Module Developer's Guide

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/Documentation#4]
I'd like to see a checklist of sorts guiding users through what modifications are expected and necessary for creating a new module.

Example: a user needs to modify To Table to correctly display their data, validate.vi to add in any checks for bad configuration (and the detail that any error thrown by validate.vi will cause the red X over the module's glyph in the configuration tree), etc.

**Comment by SimonRPSM** [comment]
Should specifics on things within the guide be added to this issue, or should they be added as separate issues?

For example, showing someone how to modify the To String VI.

@Beazurt

**Comment by theSloopJohnB** [comment]
Closed by #35!
