### ISSUE TITLE
Part 1 step 2 of Hands on mentions missing File Name Prefix template requirement

### ISSUE THREAD

**Issue by MichaelAivaliotis** [LabVIEW-DCAF/Documentation#41]
It seems the File Name Prefix requirement in the Basic Execution Template was removed as mentioned here:
[https://github.com/LabVIEW-DCAF/DCAF-Project-Templates/issues/32](https://github.com/LabVIEW-DCAF/DCAF-Project-Templates/issues/32)
However the Hands On documentation instructs to add a prefix (TCRL) which cannot be done in the newest template. See Part 1 step 2 of Hands on.

**Comment by becega** [comment]
We will update this when we are doing the movements and changes mentioned in issues 76 to 78
